version: "3.7"
services:
  attacker:
    build:
      context: attacker
      dockerfile: Dockerfile
    volumes:
      - ./attacker/run.sh:/app/run.sh
    networks:
      - envoymesh
    tty: true
    depends_on:
      - web

  envoy-gateway:
    # https://github.com/envoyproxy/envoy/commit/a2a1e3eed4214a38608ec223859fcfa8fb679b14
    # = 1.19
    image: envoyproxy/envoy-dev:a2a1e3eed4214a38608ec223859fcfa8fb679b14
    networks:
      - envoymesh
    volumes:
      - ./envoy-gateway/envoy.yaml:/etc/envoy/envoy.yaml
    expose:
      - 8000
      - 9090
    ports:
      # Debug
      # - 8000:8000
      - 9091:9090
    depends_on:
      - envoy-proxy-pure
      - envoy-proxy-compression

  envoy-proxy-pure:
    # https://github.com/envoyproxy/envoy/commit/a2a1e3eed4214a38608ec223859fcfa8fb679b14
    # = 1.19
    image: envoyproxy/envoy-dev:a2a1e3eed4214a38608ec223859fcfa8fb679b14
    networks:
      - envoymesh
    volumes:
      - ./envoy-proxy-pure/envoy.yaml:/etc/envoy/envoy.yaml
    expose:
      - 8000
      - 9090
    ports:
      - 9092:9090
    depends_on:
      - web

  envoy-proxy-compression:
    # https://github.com/envoyproxy/envoy/commit/a2a1e3eed4214a38608ec223859fcfa8fb679b14
    # = 1.19
    image: envoyproxy/envoy-dev:a2a1e3eed4214a38608ec223859fcfa8fb679b14
    networks:
      - envoymesh
    volumes:
      - ./envoy-proxy-compression/envoy.yaml:/etc/envoy/envoy.yaml
    expose:
      - 8000
      - 9090
    ports:
      - 9093:9090
    depends_on:
      - web

  web:
    build:
      context: web
      dockerfile: Dockerfile
    networks:
      - envoymesh
    environment:
      - PORT=80
    expose:
      - 80
    volumes:
      - ./web:/app
    tty: true

  grafana:
    image: grafana/grafana-oss:8.3.3
    networks:
      - envoymesh
    ports:
      - "5000:3000"
    depends_on:
      - prometheus
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning

  prometheus:
    image: prom/prometheus:v2.32.1
    networks:
      - envoymesh
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

networks:
  envoymesh: {}
