version: "3.7"
services:
  attacker:
    build:
      context: attacker
      dockerfile: Dockerfile
    networks:
      - envoymesh
    command: ["echo", "'docker compose run attacker bash'"]

  envoy-gateway:
    # https://github.com/envoyproxy/envoy/commit/a2a1e3eed4214a38608ec223859fcfa8fb679b14
    image: envoyproxy/envoy-dev:a2a1e3eed4214a38608ec223859fcfa8fb679b14
    networks:
      - envoymesh
    volumes:
      - ./envoy-gateway/envoy.yaml:/etc/envoy/envoy.yaml
    expose:
      - 8000
      - 9090
    restart: "always"

  envoy-proxy:
    # https://github.com/envoyproxy/envoy/commit/a2a1e3eed4214a38608ec223859fcfa8fb679b14
    image: envoyproxy/envoy-dev:a2a1e3eed4214a38608ec223859fcfa8fb679b14
    networks:
      - envoymesh
    volumes:
      - ./envoy-proxy/envoy.yaml:/etc/envoy/envoy.yaml
    expose:
      - 8000
      - 9090
    restart: "always"

  web:
    build:
      context: web
      dockerfile: Dockerfile
    networks:
      - envoymesh
    environment:
      - PORT=80
    volumes:
      - ./web:/app

  grafana:
    image: grafana/grafana-oss:8.3.3
    networks:
      - envoymesh
    ports:
      - "5000:3000"
    depends_on:
      - prometheus
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning

  prometheus:
    image: prom/prometheus:v2.32.1
    networks:
      - envoymesh
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - web

networks:
  envoymesh: {}
