global:
  scrape_interval: 1s
scrape_configs:
  - job_name: "web"
    static_configs:
      - targets: ["host.docker.internal:3000"]

  - job_name: "envoy"
    metrics_path: /stats/prometheus
    scheme: http
    static_configs:
      - targets:
          - "envoy:9090"
        labels:
          service: envoy
