{
 "title": "Envoy Monitor All",
 "time": { "from": "2022-03-17T05:08:28.873Z", "to": "2022-03-17T05:15:27.414Z" },
 "panels": [
  {
   "title": "Upstream - Sent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "envoy_cluster_upstream_cx_tx_bytes_total{}",
     "legendFormat": "{{instance}} → {{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Upstream - Received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "envoy_cluster_upstream_cx_rx_bytes_total{}",
     "legendFormat": "{{envoy_cluster_name}} → {{instance}}"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "envoy_server_memory_heap_size{}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "envoy_server_memory_allocated{}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Upstream Network Traffic (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(envoy_cluster_upstream_cx_rx_bytes_total{}[1m])",
     "legendFormat": "{{envoy_cluster_name}} → {{instance}}"
    }
   ]
  },
  {
   "title": "Downstream Network Traffic (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(envoy_http_downstream_cx_rx_bytes_total{envoy_http_conn_manager_prefix=\"ingress_http\"}[1m])",
     "legendFormat": "downstream → {{instance}}"
    }
   ]
  },
  {
   "title": "Request Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "msec" } },
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_rq_time_sum[15s])",
     "legendFormat": "{{instance}} → {{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "rate(envoy_http_downstream_rq_time_sum{envoy_http_conn_manager_prefix=\"ingress_http\"}[15s])",
     "legendFormat": "{{instance}} → Downstream"
    }
   ]
  },
  {
   "title": "Request Per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "irate(envoy_cluster_upstream_rq_total{}[1m])",
     "legendFormat": "{{instance}} → {{envoy_cluster_name}}"
    }
   ]
  }
 ]
}